###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    _org.springframework: warn
    org.springframework: warn
    org.springframework.jdbc.datasource.DataSourceTransactionManager: info
    org.springframework.beans.factory: warn
    com.zaxxer.hikari: info
    reactor.util.Loggers: info
    org.hibernate.validator: warn
    io.lettuce: warn
    io.netty: warn
    springfox.documentation: warn
    schemacrawler: error
    us.fatehi: error
    org.clever.task.core.TaskInstance: info
    org.clever.task.core.DaemonExecutor: info
    org.clever: debug

###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 18081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: false

###################################################################################
### management配置
###################################################################################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      root: true
      jvm: false
      system: false
      process: false
      logback: false
      jdbc: false
      hikaricp: false
      tomcat: false
      http: false
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 60s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 3s, 4s, 5s, 10s, 15s, 20s, 30s, 50s

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: fast-api-demo
  aop.proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: 'data/temp'
  mvc:
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  web:
    resources:
      static-locations:
        - 'classpath:/META-INF/resources/'
        - 'classpath:/resources/'
        - 'classpath:/static/'
        - 'classpath:/public/'
      chain:
        cache: false
        compressed: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.201:12000/fast-api
    username: fast-api
    password: Aa123456!
    hikari:
      pool-name: defaultDataSource
      data-source-properties:
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf-8
        zeroDateTimeBehavior: convert_to_null
        useSSL: false
        useCursorFetch: true
      auto-commit: false
      maximum-pool-size: 1
      minimum-idle: 1
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.1.201
    port: 12001
    password: a123456!@#
    lettuce.pool:
      min-idle: 2
      max-active: 32

###################################################################################
### clever
###################################################################################
clever:
  hot-reload:
    dev-mode: true
    root-paths: [ './clever-graaljs-fast-api-demo/src/main/groovy' ]
    http-route-modules:
      - 'org.clever.graaljs.fast.api.demo.HttpRouteDemo'
  fast-api:
    namespace: 'default'
    scan-interval: 3s
    preload: false
    script-engine:
      max-wait-millis: 1000
      min-idle: 2
      max-idle: 16
      max-total: 200
      test-on-return: true
    mvc:
      prefix: '/api'
      cors:
        allowed-origin-patterns: [ '*' ]
        allowed-methods: [ '*' ]
        allowed-headers: [ '*' ]
        exposed-headers: [ 'set-cookie' ]
        allow-credentials: true
    multiple-jdbc:
      disable: false
      default-name: default
      global:
        driver-class-name: com.mysql.cj.jdbc.Driver
        data-source-properties:
          serverTimezone: GMT+8
          useUnicode: true
          characterEncoding: utf-8
          zeroDateTimeBehavior: convert_to_null
          useSSL: false
          useCursorFetch: true
        auto-commit: false
        maximum-pool-size: 100
        minimum-idle: 5
        max-lifetime: 1800000
        connection-test-query: SELECT 1
      jdbc-map:
        default:
          jdbc-url: jdbc:mysql://192.168.1.201:12000/test-data
          username: test-data
          password: Aa123456!
    multiple-redis:
      disable: false
      default-name: default
      global:
        database: 0
        port: 6379
        lettuce:
          pool:
            max-active: 16
            max-idle: 8
            min-idle: 1
      redis-map:
        default:
          host: 192.168.1.201
          port: 12001
          password: a123456!@#
          lettuce.pool:
            min-idle: 2
            max-active: 32
    task-config:
      instance-name: n01
      heartbeat-interval: 3s
      scheduler-executor-pool-size: 8
      job-executor-pool-size: 32
      load-weight: 1
      max-concurrent: 10240
